"""Renamed image_url to image_path

Revision ID: 61517890934b
Revises: 75dd48b5f08f
Create Date: 2025-05-06 13:58:37.025769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61517890934b'
down_revision = '75dd48b5f08f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted to rename column ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.alter_column('image_url', new_column_name='image_path')

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.alter_column('image_path', new_column_name='image_url')

    # ### end Alembic commands ###
