"""Temporarily removed date from Task to fix later

Revision ID: c27f9c037a4c
Revises: 04ce47c1e61b
Create Date: 2025-05-16 23:23:42.523537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c27f9c037a4c'
down_revision = '04ce47c1e61b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=False))

    # ### end Alembic commands ###
