"""added images and shares tables

Revision ID: cbe995dcf42c
Revises: 61517890934b
Create Date: 2025-05-10 17:19:23.713107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe995dcf42c'
down_revision = '61517890934b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('image_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('shares',
    sa.Column('share_type', sa.String(length=10), nullable=False),
    sa.Column('trade_or_image_id', sa.Integer(), nullable=False),
    sa.Column('user_id_shared_to', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_shared_to'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('share_type', 'trade_or_image_id', 'user_id_shared_to')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_trade_date', ['user_id', 'trade_date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_trade_date', type_='unique')

    op.drop_table('shares')
    op.drop_table('images')
    # ### end Alembic commands ###
